spring:
  application:
    name: builders-sas-api-reactive

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/builders_sas
    username: postgres
    password: postgres

  sql:
    init:
      mode: never

server:
  port: 9090

logging:
  level:
    root: INFO
    io.r2dbc.postgresql: DEBUG
    com.builderssas: DEBUG
